/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VnOverlayIndexRouteImport } from './routes/vnOverlay/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VnOverlayIndexRoute = VnOverlayIndexRouteImport.update({
  id: '/vnOverlay/',
  path: '/vnOverlay/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vnOverlay': typeof VnOverlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vnOverlay': typeof VnOverlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vnOverlay/': typeof VnOverlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vnOverlay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vnOverlay'
  id: '__root__' | '/' | '/vnOverlay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VnOverlayIndexRoute: typeof VnOverlayIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vnOverlay/': {
      id: '/vnOverlay/'
      path: '/vnOverlay'
      fullPath: '/vnOverlay'
      preLoaderRoute: typeof VnOverlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VnOverlayIndexRoute: VnOverlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
