/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOfflineRouteImport } from './routes/_layout/offline'
import { Route as LayoutTextHookerSessionIdIndexRouteImport } from './routes/_layout/text-hooker.$sessionId.index'
import { Route as LayoutTextHookerSessionIdEditRouteImport } from './routes/_layout/text-hooker.$sessionId.edit'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOfflineRoute = LayoutOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTextHookerSessionIdIndexRoute =
  LayoutTextHookerSessionIdIndexRouteImport.update({
    id: '/text-hooker/$sessionId/',
    path: '/text-hooker/$sessionId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTextHookerSessionIdEditRoute =
  LayoutTextHookerSessionIdEditRouteImport.update({
    id: '/text-hooker/$sessionId/edit',
    path: '/text-hooker/$sessionId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/offline': typeof LayoutOfflineRoute
  '/settings': typeof LayoutSettingsRoute
  '/text-hooker/$sessionId/edit': typeof LayoutTextHookerSessionIdEditRoute
  '/text-hooker/$sessionId/': typeof LayoutTextHookerSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/offline': typeof LayoutOfflineRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/text-hooker/$sessionId/edit': typeof LayoutTextHookerSessionIdEditRoute
  '/text-hooker/$sessionId': typeof LayoutTextHookerSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/offline': typeof LayoutOfflineRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/text-hooker/$sessionId/edit': typeof LayoutTextHookerSessionIdEditRoute
  '/_layout/text-hooker/$sessionId/': typeof LayoutTextHookerSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offline'
    | '/settings'
    | '/text-hooker/$sessionId/edit'
    | '/text-hooker/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/offline'
    | '/settings'
    | '/'
    | '/text-hooker/$sessionId/edit'
    | '/text-hooker/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/offline'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/text-hooker/$sessionId/edit'
    | '/_layout/text-hooker/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offline': {
      id: '/_layout/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof LayoutOfflineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/text-hooker/$sessionId/': {
      id: '/_layout/text-hooker/$sessionId/'
      path: '/text-hooker/$sessionId'
      fullPath: '/text-hooker/$sessionId/'
      preLoaderRoute: typeof LayoutTextHookerSessionIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/text-hooker/$sessionId/edit': {
      id: '/_layout/text-hooker/$sessionId/edit'
      path: '/text-hooker/$sessionId/edit'
      fullPath: '/text-hooker/$sessionId/edit'
      preLoaderRoute: typeof LayoutTextHookerSessionIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutOfflineRoute: typeof LayoutOfflineRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTextHookerSessionIdEditRoute: typeof LayoutTextHookerSessionIdEditRoute
  LayoutTextHookerSessionIdIndexRoute: typeof LayoutTextHookerSessionIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOfflineRoute: LayoutOfflineRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTextHookerSessionIdEditRoute: LayoutTextHookerSessionIdEditRoute,
  LayoutTextHookerSessionIdIndexRoute: LayoutTextHookerSessionIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
