/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOfflineRouteImport } from './routes/_layout/offline'
import { Route as LayoutTextHookerSessionIdRouteImport } from './routes/_layout/text-hooker.$sessionId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOfflineRoute = LayoutOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTextHookerSessionIdRoute =
  LayoutTextHookerSessionIdRouteImport.update({
    id: '/text-hooker/$sessionId',
    path: '/text-hooker/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/offline': typeof LayoutOfflineRoute
  '/settings': typeof LayoutSettingsRoute
  '/text-hooker/$sessionId': typeof LayoutTextHookerSessionIdRoute
}
export interface FileRoutesByTo {
  '/offline': typeof LayoutOfflineRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/text-hooker/$sessionId': typeof LayoutTextHookerSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/offline': typeof LayoutOfflineRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/text-hooker/$sessionId': typeof LayoutTextHookerSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offline' | '/settings' | '/text-hooker/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/offline' | '/settings' | '/' | '/text-hooker/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/offline'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/text-hooker/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offline': {
      id: '/_layout/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof LayoutOfflineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/text-hooker/$sessionId': {
      id: '/_layout/text-hooker/$sessionId'
      path: '/text-hooker/$sessionId'
      fullPath: '/text-hooker/$sessionId'
      preLoaderRoute: typeof LayoutTextHookerSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutOfflineRoute: typeof LayoutOfflineRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTextHookerSessionIdRoute: typeof LayoutTextHookerSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOfflineRoute: LayoutOfflineRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTextHookerSessionIdRoute: LayoutTextHookerSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
